### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  Running setup.py install for tensorflow-gpu: started
  Running setup.py install for tensorflow-gpu: finished with status 'error'


  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-txgsrdfh\tensorflow-gpu_dcc0c713bdb045e8a344ddf77c822b65\setup.py", line 37, in <module>
          raise Exception(TF_REMOVAL_WARNING)
      Exception:
      
      The "tensorflow-gpu" package has been removed!
      
      Please install "tensorflow" instead.
      
      Other than the name, the two packages have been identical
      since TensorFlow 2.1, or roughly since Sep 2019. For more
      information, see: pypi.org/project/tensorflow-gpu
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  error: subp

In [3]:
import tensorflow as tf
print(tf.__version__)


2.15.1


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[280, 51, 35, 423], [280, 51, 35, 47], [280, 498, 35, 23], [462, 302, 380, 287, 322], [462, 302, 380, 287, 176], [59, 280, 156, 35, 304], [343, 479, 308, 287]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 280  51  35 423]
 [  0   0   0   0 280  51  35  47]
 [  0   0   0   0 280 498  35  23]
 [  0   0   0 462 302 380 287 322]
 [  0   0   0 462 302 380 287 176]
 [  0   0   0  59 280 156  35 304]
 [  0   0   0   0 343 479 308 287]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 280,  51,  35, 423])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 402ms/step


array([[ 0.02530635, -0.00472463,  0.02741739, -0.01249427,  0.02710079,
        -0.01345848, -0.0003565 , -0.01120494, -0.04765525, -0.00350251],
       [ 0.02530635, -0.00472463,  0.02741739, -0.01249427,  0.02710079,
        -0.01345848, -0.0003565 , -0.01120494, -0.04765525, -0.00350251],
       [ 0.02530635, -0.00472463,  0.02741739, -0.01249427,  0.02710079,
        -0.01345848, -0.0003565 , -0.01120494, -0.04765525, -0.00350251],
       [ 0.02530635, -0.00472463,  0.02741739, -0.01249427,  0.02710079,
        -0.01345848, -0.0003565 , -0.01120494, -0.04765525, -0.00350251],
       [ 0.03607016,  0.04824716,  0.01427306,  0.00279273,  0.03320486,
        -0.03521453,  0.02083944,  0.01797675, -0.00407379, -0.04244763],
       [-0.04869413,  0.04702226,  0.01349585, -0.01253567, -0.00453193,
        -0.01112161, -0.01959152,  0.01654562,  0.00421198, -0.00138368],
       [-0.02867683, -0.01180737,  0.01183612, -0.0016561 ,  0.02432128,
        -0.04978555, -0.01905043,  0.04217939

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 190ms/step
[[[ 0.02530635 -0.00472463  0.02741739 -0.01249427  0.02710079
   -0.01345848 -0.0003565  -0.01120494 -0.04765525 -0.00350251]
  [ 0.02530635 -0.00472463  0.02741739 -0.01249427  0.02710079
   -0.01345848 -0.0003565  -0.01120494 -0.04765525 -0.00350251]
  [ 0.02530635 -0.00472463  0.02741739 -0.01249427  0.02710079
   -0.01345848 -0.0003565  -0.01120494 -0.04765525 -0.00350251]
  [ 0.02530635 -0.00472463  0.02741739 -0.01249427  0.02710079
   -0.01345848 -0.0003565  -0.01120494 -0.04765525 -0.00350251]
  [ 0.03607016  0.04824716  0.01427306  0.00279273  0.03320486
   -0.03521453  0.02083944  0.01797675 -0.00407379 -0.04244763]
  [-0.04869413  0.04702226  0.01349585 -0.01253567 -0.00453193
   -0.01112161 -0.01959152  0.01654562  0.00421198 -0.00138368]
  [-0.02867683 -0.01180737  0.01183612 -0.0016561   0.02432128
   -0.04978555 -0.01905043  0.04217939 -0.03282036  0.04009164]
  [-0.00804349 -0.04381187 -0.03228257  0.0228712   0.0021

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 280,  51,  35, 423])

In [19]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 112ms/step
[[ 0.02530635 -0.00472463  0.02741739 -0.01249427  0.02710079 -0.01345848
  -0.0003565  -0.01120494 -0.04765525 -0.00350251]
 [ 0.02530635 -0.00472463  0.02741739 -0.01249427  0.02710079 -0.01345848
  -0.0003565  -0.01120494 -0.04765525 -0.00350251]
 [ 0.02530635 -0.00472463  0.02741739 -0.01249427  0.02710079 -0.01345848
  -0.0003565  -0.01120494 -0.04765525 -0.00350251]
 [ 0.02530635 -0.00472463  0.02741739 -0.01249427  0.02710079 -0.01345848
  -0.0003565  -0.01120494 -0.04765525 -0.00350251]
 [ 0.03607016  0.04824716  0.01427306  0.00279273  0.03320486 -0.03521453
   0.02083944  0.01797675 -0.00407379 -0.04244763]
 [-0.04869413  0.04702226  0.01349585 -0.01253567 -0.00453193 -0.01112161
  -0.01959152  0.01654562  0.00421198 -0.00138368]
 [-0.02867683 -0.01180737  0.01183612 -0.0016561   0.02432128 -0.04978555
  -0.01905043  0.04217939 -0.03282036  0.04009164]
 [-0.00804349 -0.04381187 -0.03228257  0.0228712   0.00219171  0.0055170

In [20]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]